package main

import (
	"bufio"
	"fmt"
	"log"
	//"math"
	"math/rand"
	"os"
	//"strcn" //забыл как пишется название пакета
	"strconv"
	"strings"
	"time"
)

func main() {

	seconds := time.Now().Unix()
	rand.Seed(seconds)
	guessNumber := rand.Intn(100) + 1

	fmt.Println()
	fmt.Println("The number, that was generated is: ", guessNumber) //забыл запятую, /n ставится перед скобками, а не за кавычками

	fmt.Println("Program generated a number from 1 to 100.\nTry to guess what the number is.")
	fmt.Println("You have only 10 attempts to guess, what the number is.\nSo, let's go: insert a number from 1 to 100, please...")

	for attempts := 0; attempts < 10; attempts++ {
		reader := bufio.NewReader(os.Stdin)
		//element, err := bufferReader.ReadString('\n')
		//stringFromConsole1, err := reader.NewReaderString('\n')// не правильно по памяти написал метод - это не объект, а метод.
		stringFromConsole1, err := reader.ReadString('\n')

		if err != nil {
			log.Fatal("Error occured while trying to read a string from console.")
		}

		stringFromConsole2 := strings.TrimSpace(stringFromConsole1)

		numberFromString, err := strconv.Atoi(stringFromConsole2)

		if err != nil {
			log.Fatal("Error occured while trying to parse a string from console to integer.")
		}

		fmt.Println("The number, that was inserted is: ", numberFromString)

		if numberFromString < guessNumber {
			fmt.Println("The number to guess is more, than was inserted.")
			fmt.Println("You have", 9-attempts, "attempts left, try to guess the number again.") //} else { //необходимо, чтобы скобки были на одной линии с предшествующим if.
		}
		if numberFromString > guessNumber {
			fmt.Println("The number to guess is less, than was inserted.")
			fmt.Println("You have", 9-attempts, "attempts left, try to guess the number again.") //} else { //необходимо, чтобы скобки были на одной линии с предшествующим if.
		}
		if numberFromString == guessNumber {
			fmt.Println("Congratulations, you guess the number, thar was generated by this console program.")
			break
		}
	}
}
